AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Services Orders functions.
Resources:
  serviceorder:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.servicesOrders
      Runtime: nodejs8.10
      CodeUri: .
      Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:Scan'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/SamServiceOrder'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /serviceorder
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /serviceorder
            Method: GET
        Api3:
          Type: Api
          Properties:
            Path: /serviceorder/{itemId}
            Method: ANY
  SamServiceOrder:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: SamServiceOrder
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
